<?php
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CheckoutController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Authentication routes (generated by Auth::routes())
Auth::routes();

// Home route
Route::get('/', [HomeController::class, 'index'])->name('home')->middleware('auth');

// Registration and login routes
Route::post('/register', [AuthController::class, 'register']);
Route::post('/login', [AuthController::class, 'login']);

// Logout route (protected by auth middleware)
Route::middleware('auth')->post('/logout', [AuthController::class, 'logout'])->name('logout');

Route::middleware('auth')->post('/add-to-cart/{product}', [CartController::class, 'addToCart'])->name('cart.add');
Route::middleware('auth')->get('/cart', [CartController::class, 'index'])->name('cart.index');
Route::get('/cart/remove/{productId}', [CartController::class, 'removeFromCart'])->name('cart.remove');


Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout.index');
Route::post('/checkout/process', [CheckoutController::class, 'process'])->name('checkout.process');
Route::get('/order/summary', [CheckoutController::class, 'orderSummary'])->name('order.summary');


Route::get('/order-summary', [CheckoutController::class, 'showOrderSummary'])->name('order.summary');
